<?php

/**
 * Implements hook_form_alter().
 */
function webform_select2_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'webform_client_form') === 0) {
    $select2_path = $path = libraries_get_path('select2');
    $form['#attached']['js'][] = $select2_path . '/dist/js/select2.min.js';
    $form['#attached']['css'][] = $select2_path . '/dist/css/select2.min.css';
    $form['#attached']['js'][] = drupal_get_path('module', 'webform_select2') . '/webform_select2.js';
  }
}

